language: cpp

sudo: required

compiler:
    - gcc
    - clang

install:
    # CMake 3.2+
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh
    - sudo /bin/sh cmake-3.2.3-Linux-x86_64.sh --prefix=/usr/local --skip-license
    # Doxygen
    - sudo apt-get install doxygen
    - sudo pip install cookiecutter

# ...{% if false %}
# Test that the cookiecutter behaves correctly
before_script:
    - cookiecutter --no-input .
    - cd rock
    - git add *
    - make check-format
# {% endif %}

script:
    - make test
    - make doc
