language: cpp

sudo: required

compiler:
    - gcc
    - clang

install:
    - sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x
    - sudo apt-get update -qq
    - sudo apt-get install cmake
    - sudo apt-get install doxygen
    - sudo pip install cookiecutter

# Custom setup actions
# ...{% if false %}
before_script:
    - cookiecutter --no-input .
    - cd rock
# {% endif %}

script:
    - make test
    - make doc
