language: cpp

sudo: required

compiler:
    - gcc
    - clang

install:
    - sudo add-apt-repository --yes ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install cmake
    - sudo apt-get install doxygen
    - sudo pip install cookiecutter

before_script:
    - cookiecutter --no-input .
    - cd rock

script:
    - make test
    - make doc
