version: 2
jobs:

  test_and_build:
    docker:
      - image: buildpack-deps:bionic
    working_directory: /app
    environment:
      # ENVIRONMENT: staging
    steps:
      - checkout
      - run:
          name: Build deps
          command: |
            apt-get update && apt-get install -y doxygen && apt-get install -y python-pip
            pip install cookiecutter
            cookiecutter --no-input .
      - run:
          name: Conda
          command: |
            wget -c https://repo.continuum.io/archive/Anaconda3-5.3.0-Linux-x86_64.sh
            bash Anaconda3-5.3.0-Linux-x86_64.sh -b
            export PATH=~/anaconda3/bin:$PATH
            ls -la && cd rock
            conda env create —f conda/condaenv.yml
      - run:
          name: Tests
          command: |
            cd cpp/build
            cmake —build .
            ctest .


workflows:
  version: 2
  test_and_push:
    jobs:
      - test_and_build
