version: 2
jobs:

  test_and_build:
    docker:
      - image: buildpack-deps:bionic
    working_directory: /app
    environment:
      # ENVIRONMENT: staging
    steps:
      - checkout
      - run:
          name: Cookie deps
          command: |
            apt-get update && apt-get install -y python-pip
            pip install cookiecutter
            cookiecutter --no-input .
      - run:
          name: Conda
          command: |
            wget -c https://repo.continuum.io/archive/Anaconda3-5.3.0-Linux-x86_64.sh
            bash Anaconda3-5.3.0-Linux-x86_64.sh -b
            export PATH=~/anaconda3/bin:$PATH
            ls -la && cd rock/conda
            conda env create --name test --file condaenv.yaml
      # - run:
      #     name: Test
      #     command: |
      #       export PATH=~/anaconda3/bin:$PATH
      #       source activate test
      #       cd /app/rock/cpp
      #       ctest
      - run:
          name: Build
          command: |
            export PATH=~/anaconda3/bin:$PATH
            source activate test
            cd /app/rock/cpp
            cmake . -DCMAKE_BUILD_TYPE=Release
            cmake --build .

workflows:
  version: 2
  test_and_push:
    jobs:
      - test_and_build
